settings {
    logfile = "/var/log/lsyncd/lsyncd.log",
    statusFile = "/var/log/lsyncd/lsyncd.status",
    statusInterval = 5,
    nodaemon = false
}
sync {
    default.rsync,
    source = "/home/bitrix/www/",
    target = "10.0.1.221:/home/bitrix/www/",
    delay = 15,
    rsync = {
        binary = "/usr/bin/rsync",
        archive = true,
        compress = true,
        _extra = { "-e", "ssh -o StrictHostKeyChecking=no" }
    },
    exclude = { "/bitrix/cache/**", "/bitrix/managed_cache/**", "/bitrix/stack_cache/**", "/upload/**", "/bitrix/backup/**" }
}
