Import-Module ActiveDirectory

try { New-ADUser -Name 'Binali Bachatov' -DisplayName 'Бачатов Бинали Казымович' -sAMAccountName 'bachatov.bk' -UserPrincipalName 'bachatov.bk@sync.rusagroeco.ru' -Path 'OU=Users,OU=MLR1,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Svetlana Bragina' -DisplayName 'Брагина Светлана Федоровна' -sAMAccountName 'bragina.sf' -UserPrincipalName 'bragina.sf@sync.rusagroeco.ru' -Path 'OU=Users,OU=LRM,OU=STV,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Konstantin Ganyuta' -DisplayName 'Ганюта Константин Васильевич' -sAMAccountName 'ganyuta.kv' -UserPrincipalName 'ganyuta.kv@sync.rusagroeco.ru' -Path 'OU=Disabled Users,DC=sync,DC=rusagroeco,DC=ru' -Enabled $false -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Natalya Vdovydchenko' -DisplayName 'Вдовыдченко Наталья Александровна' -sAMAccountName 'vdovydchenko.na' -UserPrincipalName 'vdovydchenko.na@sync.rusagroeco.ru' -Path 'OU=Users,OU=LRM,OU=STV,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Aleksandr Gornich' -DisplayName 'Горнич Александр Валерьевич' -sAMAccountName 'gornich.av' -UserPrincipalName 'gornich.av@sync.rusagroeco.ru' -Path 'OU=Users,OU=BRG,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Дьяковская Елена Петровна' -DisplayName 'Дьяковская Елена Петровна' -sAMAccountName 'dyakovskaya_ep' -UserPrincipalName 'dyakovskaya_ep@sync.rusagroeco.ru' -Path 'OU=Disabled Users,DC=sync,DC=rusagroeco,DC=ru' -Enabled $false -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Oksana Kovalevskaya' -DisplayName 'Ковалевская Оксана Николаевна' -sAMAccountName 'kovalevskaya.on' -UserPrincipalName 'kovalevskaya.on@sync.rusagroeco.ru' -Path 'OU=Users,OU=BDN1,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Anna Kryachko' -DisplayName 'Крячко Анна Леонидовна' -sAMAccountName 'kryachko.al' -UserPrincipalName 'kryachko.al@sync.rusagroeco.ru' -Path 'OU=Users,OU=LRM,OU=STV,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Petr Kufaev' -DisplayName 'Куфаев Пётр Леонидович' -sAMAccountName 'kufaev.pl' -UserPrincipalName 'kufaev.pl@sync.rusagroeco.ru' -Path 'OU=Users,OU=BRG,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Svetlana Lazareva' -DisplayName 'Лазарева Светлана Юрьевна' -sAMAccountName 'lazareva.sy' -UserPrincipalName 'lazareva.sy@sync.rusagroeco.ru' -Path 'OU=Disabled Users,DC=sync,DC=rusagroeco,DC=ru' -Enabled $false -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Dmitriy Motorin' -DisplayName 'Моторин Дмитрий Алексеевич' -sAMAccountName 'motorin.da' -UserPrincipalName 'motorin.da@sync.rusagroeco.ru' -Path 'OU=Users,OU=BRG,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}
try { New-ADUser -Name 'Grigoriy Obryashchenko' -DisplayName 'Обрященко Григорий Павлович' -sAMAccountName 'obryashchenko.gp' -UserPrincipalName 'obryashchenko.gp@sync.rusagroeco.ru' -Path 'OU=Users,OU=BRG,OU=RND,DC=sync,DC=rusagroeco,DC=ru' -Enabled $true -AccountPassword (ConvertTo-SecureString 'ChangeMe2026!' -AsPlainText -Force) -ErrorAction SilentlyContinue } catch {}