# /etc/nginx/sites-enabled/cc_ssl
server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/nginx/ssl/cc.crt;
    ssl_certificate_key /etc/nginx/ssl/cc.key;
    root /var/www/call-center;
    index operator.html;

    location = /sip.min.js { root /var/www/fusionpbx; }
    
    location /fsws {
        proxy_pass http://127.0.0.1:9090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400s;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400s;
    }

    location / { try_files $uri $uri/ =404; }
    location = / { return 301 /operator.html; }
}
